// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwkvsktxdignudvvugbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3a3Zza3R4ZGlnbnVkdnZ1Z2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTMwNjMsImV4cCI6MjA2NjUyOTA2M30.Pcy26w3Yq6WGzj3o8TVhB4gPUt2V3t8jb1tkPBdSa_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);